blank_issues_enabled: false
contact_links:
  - name: Exfunc support
    url: https://www.exfunc.dev
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the Exfunc Agent Tools library.

      If you're having general trouble with your Exfunc integration, please reach out to support.
